# Form implementation generated from reading ui file 'Project1GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 563)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.select_candidate_label.setGeometry(QtCore.QRect(10, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_candidate_label.setFont(font)
        self.select_candidate_label.setObjectName("select_candidate_label")
        self.candidate1_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate1_radio.setGeometry(QtCore.QRect(20, 170, 111, 20))
        self.candidate1_radio.setObjectName("candidate1_radio")
        self.candidate2_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate2_radio.setGeometry(QtCore.QRect(20, 200, 95, 20))
        self.candidate2_radio.setObjectName("candidate2_radio")
        self.total_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_vote_label.setGeometry(QtCore.QRect(430, 180, 261, 221))
        self.total_vote_label.setText("")
        self.total_vote_label.setObjectName("total_vote_label")
        self.display_total_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.display_total_vote_label.setGeometry(QtCore.QRect(430, 150, 171, 16))
        self.display_total_vote_label.setObjectName("display_total_vote_label")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(300, -20, 131, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 70, 751, 451))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.vote_for_button = QtWidgets.QPushButton(parent=self.frame)
        self.vote_for_button.setGeometry(QtCore.QRect(250, 100, 101, 28))
        self.vote_for_button.setObjectName("vote_for_button")
        self.total_votes_button = QtWidgets.QPushButton(parent=self.frame)
        self.total_votes_button.setGeometry(QtCore.QRect(350, 100, 111, 28))
        self.total_votes_button.setObjectName("total_votes_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_candidate_label.setText(_translate("MainWindow", "Please select a candidate."))
        self.candidate1_radio.setText(_translate("MainWindow", "Donald Trump"))
        self.candidate2_radio.setText(_translate("MainWindow", "Joe Biden"))
        self.display_total_vote_label.setText(_translate("MainWindow", "(hide)Total Votes"))
        self.title_label.setText(_translate("MainWindow", "Voting Menu"))
        self.vote_for_button.setText(_translate("MainWindow", "Vote"))
        self.total_votes_button.setText(_translate("MainWindow", "Count votes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
