# Form implementation generated from reading ui file 'Project1GUI1.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 563)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.select_candidate_label.setGeometry(QtCore.QRect(10, 140, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_candidate_label.setFont(font)
        self.select_candidate_label.setObjectName("select_candidate_label")
        self.display_voted_for_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.display_voted_for_label.setGeometry(QtCore.QRect(10, 380, 181, 41))
        self.display_voted_for_label.setObjectName("display_voted_for_label")
        self.vote_for_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_for_button.setGeometry(QtCore.QRect(10, 350, 93, 28))
        self.vote_for_button.setObjectName("vote_for_button")
        self.candidate1_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate1_radio.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.candidate1_radio.setObjectName("candidate1_radio")
        self.candidate2_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate2_radio.setGeometry(QtCore.QRect(120, 190, 95, 20))
        self.candidate2_radio.setObjectName("candidate2_radio")
        self.other_candidate_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.other_candidate_radio.setGeometry(QtCore.QRect(210, 190, 95, 20))
        self.other_candidate_radio.setObjectName("other_candidate_radio")
        self.other_candidate_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.other_candidate_line_edit.setGeometry(QtCore.QRect(10, 220, 151, 22))
        self.other_candidate_line_edit.setObjectName("other_candidate_line_edit")
        self.candidate_entrybox_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate_entrybox_label.setGeometry(QtCore.QRect(10, 240, 261, 16))
        self.candidate_entrybox_label.setObjectName("candidate_entrybox_label")
        self.total_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_vote_label.setGeometry(QtCore.QRect(430, 180, 261, 221))
        self.total_vote_label.setText("")
        self.total_vote_label.setObjectName("total_vote_label")
        self.display_total_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.display_total_vote_label.setGeometry(QtCore.QRect(430, 150, 171, 16))
        self.display_total_vote_label.setObjectName("display_total_vote_label")
        self.total_votes_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.total_votes_button.setGeometry(QtCore.QRect(250, 450, 171, 28))
        self.total_votes_button.setObjectName("total_votes_button")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(280, -20, 131, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_candidate_label.setText(_translate("MainWindow", "Please select a candidate, if other please enter candidates name."))
        self.display_voted_for_label.setText(_translate("MainWindow", "Display who recieved vote"))
        self.vote_for_button.setText(_translate("MainWindow", "Vote"))
        self.candidate1_radio.setText(_translate("MainWindow", "Donald Trump"))
        self.candidate2_radio.setText(_translate("MainWindow", "Joe Biden"))
        self.other_candidate_radio.setText(_translate("MainWindow", "Other"))
        self.candidate_entrybox_label.setText(_translate("MainWindow", "Please enter candidate\'s First and Last name."))
        self.display_total_vote_label.setText(_translate("MainWindow", "(hide)Total Votes"))
        self.total_votes_button.setText(_translate("MainWindow", "Count votes"))
        self.title_label.setText(_translate("MainWindow", "Voting Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
