# Form implementation generated from reading ui file 'Project1GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 563)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 10, 411, 111))
        self.textEdit.setObjectName("textEdit")
        self.select_candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.select_candidate_label.setGeometry(QtCore.QRect(10, 160, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_candidate_label.setFont(font)
        self.select_candidate_label.setObjectName("select_candidate_label")
        self.display_voted_for_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.display_voted_for_label.setGeometry(QtCore.QRect(10, 390, 181, 41))
        self.display_voted_for_label.setObjectName("display_voted_for_label")
        self.vote_for_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_for_button.setGeometry(QtCore.QRect(10, 370, 93, 28))
        self.vote_for_button.setObjectName("vote_for_button")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(10, 230, 111, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(120, 230, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(220, 230, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.other_candidate_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.other_candidate_line_edit.setGeometry(QtCore.QRect(10, 260, 151, 22))
        self.other_candidate_line_edit.setObjectName("other_candidate_line_edit")
        self.candidate_entrybox_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate_entrybox_label.setGeometry(QtCore.QRect(10, 290, 261, 16))
        self.candidate_entrybox_label.setObjectName("candidate_entrybox_label")
        self.total_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_vote_label.setGeometry(QtCore.QRect(430, 210, 261, 221))
        self.total_vote_label.setText("")
        self.total_vote_label.setObjectName("total_vote_label")
        self.display_total_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.display_total_vote_label.setGeometry(QtCore.QRect(430, 170, 171, 16))
        self.display_total_vote_label.setObjectName("display_total_vote_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Please select the candidate you feel is best suited for the job.</span></p></body></html>"))
        self.select_candidate_label.setText(_translate("MainWindow", "Please select a candidate, if other please enter candidates name."))
        self.display_voted_for_label.setText(_translate("MainWindow", "Display who recieved vote"))
        self.vote_for_button.setText(_translate("MainWindow", "Vote"))
        self.radioButton.setText(_translate("MainWindow", "Donald Trump"))
        self.radioButton_2.setText(_translate("MainWindow", "Joe Biden"))
        self.radioButton_3.setText(_translate("MainWindow", "Other"))
        self.candidate_entrybox_label.setText(_translate("MainWindow", "Please enter candidate\'s First and Last name."))
        self.display_total_vote_label.setText(_translate("MainWindow", "(hide)Total Votes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
